### ISSUE TITLE
Issue with EXILED_VERSION

### ISSUE THREAD

**Issue by Vretu-Dev** [agent188/scpsl-server-docker#2]
When setting the exiled version, the server does not search for it and installs the latest version
E.g
EXILED_VERSION=5.2.2

**Comment by agent188** [comment]
Hello, EXILED_VERSION uses --target-version in args exiled installer, this bug from installer, i try update this, but not sure if this will work

**Comment by agent188** [comment]
I updated EXILED installer inside container to version 5.3.0. Try again, If the problem persists, then create an issue to [EXILED](https://github.com/Exiled-Team/EXILED)
