### ISSUE TITLE
Synology 7.1 Docker Path Error

### ISSUE THREAD

**Issue by Vretu-Dev** [agent188/scpsl-server-docker#3]
In synology 7.1 space symbol in mount is not allowed maybe use separators like "-"
![image](https://user-images.githubusercontent.com/82831707/209817050-80599ebf-fb45-4810-a051-c6aab6051751.png)

**Comment by Vretu-Dev** [comment]
Reddit discussion https://www.reddit.com/r/synology/comments/y5muk8/comment/isknaa2/

**Comment by agent188** [comment]
This directory is the server configuration of the game, it will be created automatically with spaces in any case. What if we try to escape spaces (SCP\ Secret\ Laboratory)? As such docker allows you to use spaces in the volume path

**Comment by Vretu-Dev** [comment]
> This directory is the server configuration of the game, it will be created automatically with spaces in any case. What if we try to escape spaces (SCP\ Secret\ Laboratory)? As such docker allows you to use spaces in the volume path

`LocalAdmin v. 2.5.8[2022-12-28 22:12:31.110 +00:00] Failed to read JSON config file: Access to the path '/home/scp/.config/SCP Secret Laboratory/config/' is denied.`

**Comment by Vretu-Dev** [comment]
In json file this fill double \\
![image](https://user-images.githubusercontent.com/82831707/209880087-d98c434f-d18f-4566-a7d3-024fbf4a76af.png)

**Comment by Vretu-Dev** [comment]
This is strange because when editing json file and importing configuration, the server starts, only displays a message about incorrect configuration

**Comment by agent188** [comment]
Technically docker can use spaces in volume path. Have you tried changing permissions? `sudo chmod -R 777 /scp/scp-sl-2/config`
